source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'POPupSidebar_Example', :exclusive => true do
  pod 'POPupSidebar', :path => '../'
end

target 'POPupSidebar_Tests', :exclusive => true do
  pod 'POPupSidebar', :path => '../'

  
end
